name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir -p dist
          BIN_NAME=auto-clicker
          EXT=""
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then EXT=".exe"; fi
          cp target/${{ matrix.target }}/release/$BIN_NAME$EXT dist/$BIN_NAME-${{ matrix.target }}$EXT
          cd dist && zip $BIN_NAME-${{ matrix.target }}.zip $BIN_NAME-${{ matrix.target }}$EXT

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
